<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Regression Suite" duration-ms="19545" started-at="2019-06-12T21:03:54Z" finished-at="2019-06-12T21:04:14Z">
    <groups>
    </groups>
    <test name="Regression Test Cycle-1" duration-ms="19545" started-at="2019-06-12T21:03:54Z" finished-at="2019-06-12T21:04:14Z">
      <class name="com.practice.nidhi.TestSuit.Class2">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.practice.nidhi.TestSuit.Class2@7f9a81e8]" name="beforeMethod" is-config="true" duration-ms="7441" started-at="2019-06-12T17:04:05Z" finished-at="2019-06-12T17:04:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="f()[pri:0, instance:com.practice.nidhi.TestSuit.Class2@7f9a81e8]" name="f" duration-ms="117" started-at="2019-06-12T17:04:13Z" finished-at="2019-06-12T17:04:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.practice.nidhi.TestSuit.Class2@7f9a81e8]" name="afterMethod" is-config="true" duration-ms="1002" started-at="2019-06-12T17:04:13Z" finished-at="2019-06-12T17:04:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.practice.nidhi.TestSuit.Class2 -->
      <class name="com.practice.nidhi.TestSuit.Class1">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.practice.nidhi.TestSuit.Class1@20e2cbe0]" name="beforeMethod" is-config="true" duration-ms="9762" started-at="2019-06-12T17:03:54Z" finished-at="2019-06-12T17:04:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.practice.nidhi.TestSuit.Class1@20e2cbe0]" name="f" duration-ms="179" started-at="2019-06-12T17:04:04Z" finished-at="2019-06-12T17:04:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at com.practice.nidhi.TestSuit.Class1.f(Class1.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.practice.nidhi.TestSuit.Class1@20e2cbe0]" name="afterMethod" is-config="true" duration-ms="1010" started-at="2019-06-12T17:04:04Z" finished-at="2019-06-12T17:04:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.practice.nidhi.TestSuit.Class1 -->
    </test> <!-- Regression Test Cycle-1 -->
  </suite> <!-- Regression Suite -->
</testng-results>
